server:
  port: 8082
spring:
  application:
    name: "Reportes"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
jwt:
  secret: ${JWT_SECRET:-crediya_jwt_secret_key_2024_super_secure}
  expiration: ${JWT_EXPIRATION:-3600000}
  excluded-paths:
    - /swagger-ui.html
    - /swagger-ui/**
    - /webjars/**
    - /v3/api-docs/**

security:
  rules:
    authorization:
      - path: /swagger-ui.html
        roles: [ ROLE_ANONYMOUS ]
      - path: /swagger-ui/**
        roles: [ ROLE_ANONYMOUS ]
      - path: /webjars/**
        roles: [ ROLE_ANONYMOUS ]
      - path: /v3/api-docs/**
        roles: [ ROLE_ANONYMOUS ]
