server:
  port: 8080
spring:
  application:
    name: "Reportes"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"
jwt:
  secret: "your-secret-key-that-is-at-least-256-bits-long"
  expiration: 3600000 # 1 hour in milliseconds
  excluded-paths:
    - /swagger-ui.html
    - /swagger-ui/**
    - /webjars/**
    - /v3/api-docs/**

security:
  rules:
    authorization:
      - path: /swagger-ui.html
        roles: [ROLE_ANONYMOUS]
      - path: /swagger-ui/**
        roles: [ROLE_ANONYMOUS]
      - path: /webjars/**
        roles: [ROLE_ANONYMOUS]
      - path: /v3/api-docs/**
        roles: [ROLE_ANONYMOUS]
